apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  labels:
    name: guestbook-service
    app: guestbook-app
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30018
  selector:
    name: guestbook-app-pod
    app: guestbook-app
