apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbokk-app-deployment
  labels:
    app: guestbook-app
spec:
  template:
    metadata:
      name: guestbook-app-pod
      labels:
        name: guestbook-app-pod
        app: guestbook-app
    spec:
      containers:
        - name: guestbook-app
          image: gcr.io/google-samples/gb-frontend:v4
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      name: guestbook-app-pod
      app: guestbook-app

